site_name: Performai Manual
copyright: Evil Leaker

theme:
  name: material
  logo: asset/img/common/site_logo.svg
  favicon: asset/img/common/favicon.png
  icon:
    repo: fontawesome/brands/github
    annotation: material/arrow-right-circle
  navigation_depth: 3
  palette:
    # Toggle for auto mode
    - media: "(prefers-color-scheme)"
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/brightness-auto
        name: 切换正常模式
    # Toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: pink
      toggle:
        icon: material/brightness-7
        name: 切换护眼模式
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: pink
      accent: deep blue
      toggle:
        icon: material/brightness-4
        name: 跟随系统
  features:
    - content.code.annotate
    - content.tooltips
    - content.code.copy
    - content.code.select
    - content.code.annotate

markdown_extensions:
  - abbr
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.keys
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - attr_list
  - pymdownx.emoji:
        emoji_index: !!python/name:material.extensions.emoji.twemoji
        emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - md_in_html

plugins:
  - search:
      separator: '[\s\u200b\-]'
      lang:
        - zh
        - ja
        - en

nav:
  - 首页: index.md
  - 游戏:
      - "SEGA":
          - "CHUNITHM":
              - "安装使用教程": "games/chunithm/setup.md"
              - "全国对战": "games/chunithm/national_battle.md"
  - 控制器:
      - "SEGA":
          - "CHUNITHM":
              - "(旧)TASOLLER": "controller/chunithm/controller_tasoller.md"
              - "TASOLLER PLUS": "controller/chunithm/controller_tasollerplus.md"
              - "Yubideck": "controller/chunithm/controller_yubideck.md"
              - "其他输入方式": "controller/chunithm/controller_other.md"
  - 其他:
      - "键值表": "other/key.md"